# -*- coding: utf-8 -*-
"""Fraud Detection Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LaHvwqMTs1Ws39jSLiUrH19kwdWzRp71
"""

!pip install scikit-learn pandas numpy matplotlib

from google.colab import drive
drive.mount('/content/drive')

"""Load the Dataset from ZIP"""

import zipfile
import pandas as pd

zip_path = "/content/drive/My Drive/codsoft dataset/credit_card_fraud_detection/archive.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    df = pd.read_csv(z.open("fraudTrain.csv"))

df.head()

"""Quick Dataset Check"""

print(df.shape)
print(df["is_fraud"].value_counts(normalize=True))

"""Data Cleaning & Feature Engineering"""

# Drop non-useful columns
drop_cols = [
    "Unnamed: 0", "cc_num", "first", "last",
    "street", "trans_num", "merchant"
]
df = df.drop(columns=drop_cols)

# Convert datetime
df["trans_date_trans_time"] = pd.to_datetime(df["trans_date_trans_time"])

df["hour"] = df["trans_date_trans_time"].dt.hour
df["day"] = df["trans_date_trans_time"].dt.day
df["month"] = df["trans_date_trans_time"].dt.month

df = df.drop(columns=["trans_date_trans_time", "dob"])

"""Encode Categorical Features"""

from sklearn.preprocessing import LabelEncoder

categorical_cols = df.select_dtypes(include="object").columns

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

"""Train / Test Split"""

from sklearn.model_selection import train_test_split

X = df.drop("is_fraud", axis=1)
y = df["is_fraud"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

"""Evaluation"""

from sklearn.metrics import classification_report, roc_auc_score

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    print(classification_report(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))

"""Logistic Regression"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    n_jobs=-1
)

lr.fit(X_train, y_train)
evaluate_model(lr, X_test, y_test)