# -*- coding: utf-8 -*-
"""SPAM DETECTION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Cbzb2zIjDjZhhYXhAHZ7ID_SHCwMSXF
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

from google.colab import drive
drive.mount('/content/drive')
file_path = '/content/drive/MyDrive/codsoft dataset/spam.csv'
data = pd.read_csv(file_path, encoding='latin1')

data = data[['v1','v2']]
data.columns = ['labels','message']

data['labels'] = data['labels'].map({'ham':0,'spam':1})

X_train ,X_TEST,y_train,y_test = train_test_split(data['message'],data['labels'],test_size=0.2,random_state=42)

vectorizer = TfidfVectorizer(stop_words='english',max_df = 0.7)
X_train_vector = vectorizer.fit_transform(X_train)
X_test_vector = vectorizer.transform(X_TEST)

model = MultinomialNB()
model.fit(X_train_vector,y_train)

y_pred = model.predict(X_test_vector)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("\nConfusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("\nClassification Report:\n",classification_report(y_test,y_pred))

msg = input("\nEnter a message to check (spam/ham)")
msg_vector = vectorizer.transform([msg])
prediction = model.predict(msg_vector)
if prediction[0] == 1:
    print("\nSpam Message")
else:
    print("\nNot a Spam Message")